In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Encoder data\Encoded_data.xlsx')

In [4]:
data.head()

,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,Diagnosis_Code,Procedure_Code,Number_of_Procedures,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,462337.48,28,0,937,19,981,18,968,1053,2,...,0,0,0,0,0,1,0,2021,6,46
1,1883481.30,40,2,980,2,1017,0,1289,1273,2,...,0,0,0,1,0,0,0,2025,1,2
2,1500658.89,90,0,1009,4,967,12,987,1011,1,...,0,0,0,1,0,0,0,2023,5,42
3,572237.61,49,2,998,9,981,16,1002,973,4,...,0,0,0,1,0,0,0,2021,11,5
4,2088293.84,24,0,976,4,1027,15,969,973,5,...,0,0,0,1,0,0,0,2024,3,36

In [5]:
scale_columns = [
    'Claim_Amount',
    'Patient_Age',
    'Patient_City',
    'Provider_City',
    'Diagnosis_Code',
    'Procedure_Code',
    'Number_of_Procedures',
    'Length_of_Stay_Days',
    'Deductible_Amount',
    'CoPay_Amount',
    'Number_of_Previous_Claims_Patient',
    'Number_of_Previous_Claims_Provider',
    'Provider_Patient_Distance_Miles',
    'Claim_Year',
    'Claim_Month',
    'Claim_Delay_Days'
]

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

data[scale_columns] = scaler.fit_transform(data[scale_columns])

In [7]:
data.head()

,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,Diagnosis_Code,Procedure_Code,Number_of_Procedures,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,-1.121339,-0.650370,0,-1.933469,19,-1.058893,18,-0.430195,0.399223,-1.217663,...,0,0,0,0,0,1,0,-0.796174,-0.086455,0.036400
1,0.913860,-0.194101,2,-0.733256,2,0.494558,0,2.530557,2.611934,-1.217663,...,0,0,0,1,0,0,0,1.702260,-1.550441,-1.635309
2,0.365625,1.707018,0,0.076190,4,-1.663013,12,-0.254948,-0.023204,-1.564551,...,0,0,0,1,0,0,0,0.453043,-0.379252,-0.115574
3,-0.963953,0.148100,2,-0.230841,9,-1.058893,16,-0.116595,-0.405399,-0.523887,...,0,0,0,1,0,0,0,-0.796174,1.377530,-1.521329
4,1.207168,-0.802460,0,-0.844904,4,0.926073,15,-0.420972,-0.405399,-0.176999,...,0,0,0,1,0,0,0,1.077652,-0.964847,-0.343534

In [8]:
import pickle

pickle.dump(
    scaler,
    open("scaler.pkl", "wb")
)

In [9]:
data.to_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Scaling dataset\Scaling_data.xlsx', index=False)