In [25]:
import pandas as pd
import numpy as np

In [26]:
data=pd.read_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Clean data\clean_data.xlsx')

In [27]:
data.head()

,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_Type,Provider_Specialty,...,Discharge_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles,Claim_Submitted_Late,Is_Fraudulent
0,2021-06-16,2021-05-01,2024-11-20,462337.48,28,Female,Houston,WI,Clinic,Cardiology,...,Rehab/Skilled Nursing,0,Inpatient,3440.06,824.59,0,16,939.08,True,False
1,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,Other,Washington,CO,Laboratory,Cardiology,...,Deceased,0,Outpatient,3618.40,851.43,0,6,170.40,False,True
2,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,Female,Seattle,FL,Hospital,Neurology,...,Deceased,0,Pharmacy,2442.41,616.23,0,2,549.38,True,False
3,2021-11-07,2021-11-02,2025-12-24,572237.61,49,Other,Fort Worth,MD,Specialist Office,Pediatrics,...,Deceased,0,Pharmacy,587.78,459.33,0,2,396.49,False,True
4,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,Female,New York,FL,Specialist Office,Pediatrics,...,Deceased,0,Emergency Room,3047.55,847.40,0,15,865.87,True,False

In [28]:
boolean_columns = [
    'Claim_Submitted_Late',
    'Is_Fraudulent'
]
data['Claim_Submitted_Late'] = data['Claim_Submitted_Late'].astype(int)

data['Is_Fraudulent'] = data['Is_Fraudulent'].astype(int)

In [29]:
data.head()

,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_Type,Provider_Specialty,...,Discharge_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles,Claim_Submitted_Late,Is_Fraudulent
0,2021-06-16,2021-05-01,2024-11-20,462337.48,28,Female,Houston,WI,Clinic,Cardiology,...,Rehab/Skilled Nursing,0,Inpatient,3440.06,824.59,0,16,939.08,1,0
1,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,Other,Washington,CO,Laboratory,Cardiology,...,Deceased,0,Outpatient,3618.40,851.43,0,6,170.40,0,1
2,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,Female,Seattle,FL,Hospital,Neurology,...,Deceased,0,Pharmacy,2442.41,616.23,0,2,549.38,1,0
3,2021-11-07,2021-11-02,2025-12-24,572237.61,49,Other,Fort Worth,MD,Specialist Office,Pediatrics,...,Deceased,0,Pharmacy,587.78,459.33,0,2,396.49,0,1
4,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,Female,New York,FL,Specialist Office,Pediatrics,...,Deceased,0,Emergency Room,3047.55,847.40,0,15,865.87,1,0

In [30]:
from sklearn.preprocessing import LabelEncoder
label_columns = [
    'Patient_Gender',
    'Admission_Type',
    'Service_Type'
]



le = LabelEncoder()

for col in label_columns:
    data[col] = le.fit_transform(data[col])

In [31]:
data.head()

,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_Type,Provider_Specialty,...,Discharge_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles,Claim_Submitted_Late,Is_Fraudulent
0,2021-06-16,2021-05-01,2024-11-20,462337.48,28,0,Houston,WI,Clinic,Cardiology,...,Rehab/Skilled Nursing,0,2,3440.06,824.59,0,16,939.08,1,0
1,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,2,Washington,CO,Laboratory,Cardiology,...,Deceased,0,4,3618.40,851.43,0,6,170.40,0,1
2,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,0,Seattle,FL,Hospital,Neurology,...,Deceased,0,5,2442.41,616.23,0,2,549.38,1,0
3,2021-11-07,2021-11-02,2025-12-24,572237.61,49,2,Fort Worth,MD,Specialist Office,Pediatrics,...,Deceased,0,5,587.78,459.33,0,2,396.49,0,1
4,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,0,New York,FL,Specialist Office,Pediatrics,...,Deceased,0,1,3047.55,847.40,0,15,865.87,1,0

In [32]:
onehot_columns = [
    'Provider_Type',
    'Provider_Specialty',
    'Discharge_Type'
]
data = pd.get_dummies(
    data,
    columns=onehot_columns,
    drop_first=True
)

In [33]:
data.head()

,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,...,Provider_Specialty_Oncology,Provider_Specialty_Orthopedics,Provider_Specialty_Pediatrics,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility
0,2021-06-16,2021-05-01,2024-11-20,462337.48,28,0,Houston,WI,Los Angeles,WA,...,False,False,False,False,False,False,False,False,True,False
1,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,2,Washington,CO,Dallas,AZ,...,False,False,False,False,False,False,True,False,False,False
2,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,0,Seattle,FL,Phoenix,NC,...,False,False,False,False,False,False,True,False,False,False
3,2021-11-07,2021-11-02,2025-12-24,572237.61,49,2,Fort Worth,MD,Los Angeles,TX,...,False,False,True,False,False,False,True,False,False,False
4,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,0,New York,FL,San Diego,PA,...,False,False,True,False,False,False,True,False,False,False

In [34]:
high_cardinality_columns = [
    'Patient_City',
    'Provider_City',
    'Diagnosis_Code',
    'Procedure_Code'
]

for col in high_cardinality_columns:

    freq = data[col].value_counts()

    data[col] = data[col].map(freq)

In [35]:
data.head()

,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,...,Provider_Specialty_Oncology,Provider_Specialty_Orthopedics,Provider_Specialty_Pediatrics,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility
0,2021-06-16,2021-05-01,2024-11-20,462337.48,28,0,937,WI,981,WA,...,False,False,False,False,False,False,False,False,True,False
1,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,2,980,CO,1017,AZ,...,False,False,False,False,False,False,True,False,False,False
2,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,0,1009,FL,967,NC,...,False,False,False,False,False,False,True,False,False,False
3,2021-11-07,2021-11-02,2025-12-24,572237.61,49,2,998,MD,981,TX,...,False,False,True,False,False,False,True,False,False,False
4,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,0,976,FL,1027,PA,...,False,False,True,False,False,False,True,False,False,False

In [36]:
data['Claim_Year'] = data['Claim_Date'].dt.year
data['Claim_Month'] = data['Claim_Date'].dt.month

data['Claim_Delay_Days'] = (
    data['Claim_Date'] - data['Service_Date']
).dt.days

In [37]:
data.drop(columns=[
    'Claim_Date',
    'Service_Date',
    'Policy_Expiration_Date'
], inplace=True)

In [38]:
data.head(10)

,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,Diagnosis_Code,Procedure_Code,Number_of_Procedures,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,462337.48,28,0,937,WI,981,WA,968,1053,2,...,False,False,False,False,False,True,False,2021,6,46
1,1883481.30,40,2,980,CO,1017,AZ,1289,1273,2,...,False,False,False,True,False,False,False,2025,1,2
2,1500658.89,90,0,1009,FL,967,NC,987,1011,1,...,False,False,False,True,False,False,False,2023,5,42
3,572237.61,49,2,998,MD,981,TX,1002,973,4,...,False,False,False,True,False,False,False,2021,11,5
4,2088293.84,24,0,976,FL,1027,PA,969,973,5,...,False,False,False,True,False,False,False,2024,3,36
5,2473391.25,75,1,984,DC,1027,IL,1026,1053,1,...,False,False,False,True,False,False,False,2021,12,37
6,994761.24,0,2,987,CO,999,TX,976,1252,10,...,False,False,False,False,True,False,False,2021,12,61
7,1673148.85,80,0,976,IN,992,WI,1002,980,2,...,False,True,False,False,False,True,False,2024,7,82
8,2421162.18,55,2,998,MD,1041,NY,1287,962,2,...,False,False,True,False,True,False,False,2022,7,58
9,1081719.49,73,1,1047,CA,1038,CA,943,945,8,...,False,False,False,False,False,False,False,2020,4,42

In [39]:
bool_cols = data.select_dtypes(include='bool').columns

data[bool_cols] = data[bool_cols].astype(int)

In [40]:
data.head(5)

,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,Diagnosis_Code,Procedure_Code,Number_of_Procedures,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,462337.48,28,0,937,WI,981,WA,968,1053,2,...,0,0,0,0,0,1,0,2021,6,46
1,1883481.30,40,2,980,CO,1017,AZ,1289,1273,2,...,0,0,0,1,0,0,0,2025,1,2
2,1500658.89,90,0,1009,FL,967,NC,987,1011,1,...,0,0,0,1,0,0,0,2023,5,42
3,572237.61,49,2,998,MD,981,TX,1002,973,4,...,0,0,0,1,0,0,0,2021,11,5
4,2088293.84,24,0,976,FL,1027,PA,969,973,5,...,0,0,0,1,0,0,0,2024,3,36

In [41]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data['Patient_State'] = le.fit_transform(data['Patient_State'])

data['Provider_State'] = le.fit_transform(data['Provider_State'])

In [42]:
data.head()

,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,Patient_State,Provider_City,Provider_State,Diagnosis_Code,Procedure_Code,Number_of_Procedures,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,462337.48,28,0,937,19,981,18,968,1053,2,...,0,0,0,0,0,1,0,2021,6,46
1,1883481.30,40,2,980,2,1017,0,1289,1273,2,...,0,0,0,1,0,0,0,2025,1,2
2,1500658.89,90,0,1009,4,967,12,987,1011,1,...,0,0,0,1,0,0,0,2023,5,42
3,572237.61,49,2,998,9,981,16,1002,973,4,...,0,0,0,1,0,0,0,2021,11,5
4,2088293.84,24,0,976,4,1027,15,969,973,5,...,0,0,0,1,0,0,0,2024,3,36

In [43]:
data['Is_Fraudulent'].value_counts()

Is_Fraudulent
0    15089
1     5011
Name: count, dtype: int64

In [44]:
data.to_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Encoder data\Encoded_data.xlsx', index=False)

In [46]:
from sklearn.preprocessing import LabelEncoder
import pickle

encoders = {}

label_columns = [
    'Patient_State',
    'Provider_State'
]

for col in label_columns:

    le = LabelEncoder()

    data[col] = le.fit_transform(data[col])

    encoders[col] = le

# Save the encoders
with open(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\6.Artifacts\encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)